;; URL escape/unescape
(defun unescape (start end)
  (interactive "r")
  (let (src (ret "") s e)
    (setq src (buffer-substring-no-properties start end))
    (while (string-match "%[a-zA-Z0-9][a-zA-Z0-9]" src)
      (setq s (match-beginning 0))
      (setq e (match-end 0))
      (setq ret (concat ret (substring src 0 s)))
      (setq ret (concat ret (format "%c" (string-to-number (substring src (1+ s) e) 16))))
      (setq src (substring src e))
      )
    (setq ret (concat ret src))
    (insert-string "\n")
    (insert-string ret)
    )
  )
(defun escape (start end)
  (interactive "r")
  (let (src _isacii _escape)
    (setq src (buffer-substring-no-properties start end))
    (setq _isascii '(lambda (c)
          (cond
           ((and (<= ?A c)(<= c ?Z)) t)
           ((and (<= ?a c)(<= c ?z)) t)
           ((and (<= ?0 c)(<= c ?9)) t)
           (t nil))))
    (setq _escape '(lambda (l)
                     (cond
                      ((null l) nil)
                      (t (cons 
                          (if (funcall _isascii (car l)) (format "%c" (car l)) (format "%%%02x" (car l)))
                          (funcall _escape (cdr l))
                          )
                         ))))
    (insert-string "\n")
    (insert-string (eval (cons 'concat (funcall _escape (string-to-list src)))))
))

